import './globals.css';
import Navbar from '../components/Nav';
import { QuotesProvider } from './QuotesContext';
import React from 'react';
import { AuthProvider } from '../context/AuthContext';
import { Inter, Playfair_Display } from 'next/font/google';

export const metadata = {
  title: 'Random Quotes App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const playfair = Playfair_Display({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-serif',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='light'>
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
        <AuthProvider>
          <QuotesProvider>
            <Navbar />
            {children}
          </QuotesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
